package com.mycompany.caassignment.hibernate;

// Generated 12-Apr-2016 20:37:36 by Hibernate Tools 4.3.1



/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer id;
     private String email;
     private byte[] password;
     private Person person;

    public Member() {
    }

	
    public Member(byte[] password) {
        this.password = password;
    }
    public Member(String email, byte[] password, Person person) {
       this.email = email;
       this.password = password;
       this.person = person;
    }

    Member(String email, byte[] password) {
       this.password = password;
       this.email = email;
       this.person = null;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
}