package com.mycompany.caassignment.hibernate;
// Generated 15-Mar-2016 22:58:49 by Hibernate Tools 4.3.1



/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer id;
     private String email;
     private byte[] password;

    public Member() {
    }

	
    public Member(byte[] password) {
        this.password = password;
    }
    public Member(String email, byte[] password) {
       this.email = email;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }




}


