package com.mycompany.caassignment.hibernate;
// Generated 12-Apr-2016 20:37:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private Integer idmember;
     private Boolean admin;
     private String title;
     private String firstname;
     private String lastname;
     private Date dateofbirth;
     private Set policies = new HashSet(0);

    public Person() {
    }

	
    public Person(Member member) {
        this.member = member;
    }
    public Person(Member member, Integer idmember, Boolean admin, String title, String firstname, String lastname, Date dateofbirth, Set policies) {
       this.member = member;
       this.idmember = idmember;
       this.admin = admin;
       this.title = title;
       this.firstname = firstname;
       this.lastname = lastname;
       this.dateofbirth = dateofbirth;
       this.policies = policies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Integer getIdmember() {
        return this.idmember;
    }
    
    public void setIdmember(Integer idmember) {
        this.idmember = idmember;
    }
    public Boolean getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }
    public Set getPolicies() {
        return this.policies;
    }
    
    public void setPolicies(Set policies) {
        this.policies = policies;
    }
    
    public String toString() {
        return getTitle()+" "+getFirstname()+" "+getLastname();
    }




}


