package com.mycompany.caassignment.hibernate;
// Generated 12-Apr-2016 20:37:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Policy generated by hbm2java
 */
public class Policy  implements java.io.Serializable {


     private Integer id;
     private Person person;
     private boolean outsideEuUs;
     private Date start;
     private Date finish;
     private Boolean healthInsurance;
     private Set policypersons = new HashSet(0);

    public Policy() {
    }

	
    public Policy(boolean outsideEuUs) {
        this.outsideEuUs = outsideEuUs;
    }
    public Policy(Person person, boolean outsideEuUs, Date start, Date finish, Boolean healthInsurance, Set policypersons) {
       this.person = person;
       this.outsideEuUs = outsideEuUs;
       this.start = start;
       this.finish = finish;
       this.healthInsurance = healthInsurance;
       this.policypersons = policypersons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public boolean isOutsideEuUs() {
        return this.outsideEuUs;
    }
    
    public void setOutsideEuUs(boolean outsideEuUs) {
        this.outsideEuUs = outsideEuUs;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getFinish() {
        return this.finish;
    }
    
    public void setFinish(Date finish) {
        this.finish = finish;
    }
    public Boolean getHealthInsurance() {
        return this.healthInsurance;
    }
    
    public void setHealthInsurance(Boolean healthInsurance) {
        this.healthInsurance = healthInsurance;
    }
    public Set getPolicypersons() {
        return this.policypersons;
    }
    
    public void setPolicypersons(Set policypersons) {
        this.policypersons = policypersons;
    }




}


