package com.mycompany.caassignment.hibernate;
// Generated 12-Apr-2016 20:37:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Policyperson generated by hbm2java
 */
public class Policyperson  implements java.io.Serializable {


     private Integer idPolicyPerson;
     private Policy policy;
     private String title;
     private String firstname;
     private String lastname;
     private Date dateofbirth;

    public Policyperson() {
    }

	
    public Policyperson(Policy policy) {
        this.policy = policy;
    }
    public Policyperson(Policy policy, String title, String firstname, String lastname, Date dateofbirth) {
       this.policy = policy;
       this.title = title;
       this.firstname = firstname;
       this.lastname = lastname;
       this.dateofbirth = dateofbirth;
    }
   
    public Integer getIdPolicyPerson() {
        return this.idPolicyPerson;
    }
    
    public void setIdPolicyPerson(Integer idPolicyPerson) {
        this.idPolicyPerson = idPolicyPerson;
    }
    public Policy getPolicy() {
        return this.policy;
    }
    
    public void setPolicy(Policy policy) {
        this.policy = policy;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }




}


